# Generated by Django 2.0.2 on 2019-07-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fan_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=40)),
                ('tote', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='star_topic',
            name='tote',
            field=models.IntegerField(),
        ),
    ]
