# Generated by Django 2.0.2 on 2019-07-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190711_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='star_pinglun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=40)),
                ('tote', models.IntegerField()),
            ],
        ),
    ]
