# Generated by Django 2.0.2 on 2019-07-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_fan_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='huati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=40)),
                ('tote', models.IntegerField()),
            ],
        ),
    ]
